# Generated by Django 5.2 on 2025-05-15 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='api.tickettype'),
        ),
    ]
