# Generated by Django 5.2 on 2025-05-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ticket_ticket_type'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='groups',
            field=models.ManyToManyField(help_text='Grupos que podem comprar este tipo de bilhete', to='auth.group'),
        ),
    ]
